version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && \
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ".:/myapp"
      - "bundle:/myapp/vendor/bundle"
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "14321:4321"
    volumes:
      - "postgresql-db:/var/lib/postgresql/data"
    command: -p 4321
volumes:
  bundle:
    driver: local
  postgresql-db:
    driver: local
