version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && \
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    environment:
      DB_NAME: naro_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ".:/myapp"
      - "bundle:/myapp/vendor/bundle"
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  front:
    build: ./front
    command: sh -c "yarn install && yarn dev"
    volumes:
      - "./front:/front"
      # - "node-modules:/front/node_modules"
    ports:
      - "4001:4001"
    tty: true
    stdin_open: true
    init: true
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "14321:4321"
    volumes:
      - "postgresql-db:/var/lib/postgresql/data"
      - "./postgres/postgres.conf:/etc/postgresql/postgresql.conf"
      - "./postgres/log:/log"
    command: postgres -p 4321 -c 'config_file=/etc/postgresql/postgresql.conf'
volumes:
  bundle:
    driver: local
  # node-modules:
  #   driver: local
  postgresql-db:
    driver: local
